### ISSUE TITLE
mset or a pipline

### ISSUE THREAD

**Issue by amirreza8002** [valkey-io/valkey-py#102]
hi
i know this is valkey, but django-redis doesn't seem active. 
django-redis uses a pipline to do `set_many()` [here](https://github.com/jazzband/django-redis/blob/master/django_redis/client/default.py#L580-L583), but both redis-py and valkey-py have `mset()`

so i'm wondering if there is any benefit to this, or it's a mistake

**Comment by aiven-sal** [comment]
`mset` is atomic, a pipeline of "set"s isn't. So the latter may be better if _atomicity_ isn't a property you are interested in.

BTW, for generic questions about Valkey, you can take a look at https://github.com/orgs/valkey-io/discussions/categories/general . Tt's easier to get a quick response there, as there are more people involved.
