### ISSUE TITLE
ConnectionPool connection error

### ISSUE THREAD

**Issue by amirreza8002** [valkey-io/valkey-py#110]
hi
something i can't find is,
 when i [pass in connection pool](https://github.com/amirreza8002/django-valkey/blob/main/django_valkey/pool.py#L39) to `valkey.Valkey`, if the server is not available, [`connect()`](https://github.com/amirreza8002/django-valkey/blob/main/django_valkey/base_client.py#L179) won't raise an exception, and exception will be raised when i call a method like [`get(key)`](https://github.com/amirreza8002/django-valkey/blob/main/django_valkey/base_client.py#L330-L333).

but without a [connection pool](https://github.com/amirreza8002/django-valkey/blob/main/django_valkey/cluster_cache/pool.py#L28), [`connect()`](https://github.com/amirreza8002/django-valkey/blob/main/django_valkey/base_client.py#L179) will raise an error.

**Comment by amirreza8002** [comment]
on a new note, the class `valkey.cluster.NodesManager` has an options for connection pools
even the variable `VALKEY_ALLOWED_KEYS` includes connection pools

but `ValkeyCluster` and the base class don't have the option to include

now i don't insist in adding one, since there could be a reason why it's not there, but i'd like to know a workaround for the connection error problem, if there is any

**Comment by aiven-sal** [comment]
Hi, I'm sorry but I'm not sure I understand what is the problem

**Comment by aiven-sal** [comment]
What's happening here is that the non-cluster connection is performed lazily the first time that it is needed, while cluster performs the connections immediately, cause it needs to reach at least one `startup node` to be able to setup a cluster.

I don't think there is much that can be done about this. If the connection to the server doesn't work, the client doesn't work anyway. This isn't an error that you can ignore and expect valkey-py to work.

You could lazily create the cluster object when you need it, if that is the kind of behavior that you are looking for.

**Comment by amirreza8002** [comment]
hi
thank you for the time you put on this

I'll probably just document this feature as `not available for cluster`.

that is, if i can find why cluster CI is breaking  :)

anyway, thanks again 🙌
