### ISSUE TITLE
unix socket can't connect to `.sock` file in the current directory by relatice path

### ISSUE THREAD

**Issue by amirreza8002** [valkey-io/valkey-py#123]
`valkey-server --save "" --unixsocket ./valkey.sock --unixsocketperm 777`

```
from valkey import Valkey

v = Valkey.from_url("unix://valkey.sock")

# or
v = Valkey.from_url("unix://./valkey.sock")

v.set("foo", "var")
```
`valkey.exceptions.ConnectionError: Error 2 connecting to /valkey.sock. No such file or directory.`

the only way it seems to work is by giving an absolute path `"/home/user/project/..."`

**Comment by aiven-sal** [comment]
Did you try `"unix:./valkey.sock"` ? It should work according to [RC 1808](https://datatracker.ietf.org/doc/html/rfc1808.html#section-2.2).
Maybe it can be documented better.

**Comment by amirreza8002** [comment]
hi again
`v = Valkey.from_url("unix:./valkey.sock")`

thorws this error:
```
ValueError: Valkey URL must specify one of the following schemes ['valkey', 'valkeys', 'redis', 'rediss', 'unix']
```
