### ISSUE TITLE
Pypi package not available

### ISSUE THREAD

**Issue by nicc777** [valkey-io/valkey-py#13]
**Version**: any/all

**Platform**: any/all

**Description**: Package is not currently available

Example:

```shell
$ pip install valkey
ERROR: Could not find a version that satisfies the requirement valkey (from versions: none)
ERROR: No matching distribution found for valkey
```

Searching for `valkey` on PyPi produces these 2 results at the time of writing:

* https://pypi.org/project/valkey-py/
* https://pypi.org/project/pyvalkey/

**Comment by aiven-sal** [comment]
Hi! Thanks for reporting.
I can confirm that the correct package name should be just "valkey".
The package is missing at the moment, but we will build one soon.
