### ISSUE TITLE
Flaky test test_interrupted_command

### ISSUE THREAD

**Issue by aiven-sal** [valkey-io/valkey-py#131]
The [thread's join has a timeout that is too short](https://github.com/valkey-io/valkey-py/blob/950ea26ee2a06916181c7f4837e3e26630491e6e/tests/test_commands.py#L5099) and sometimes the test fails e.g.

https://github.com/valkey-io/valkey-py/actions/runs/12115916390/job/33775289852

**Comment by paulorochaoliveira** [comment]
I believe calling the join() without argument could fix the flakiness of this test. What do you think @aiven-sal ?

**Comment by paulorochaoliveira** [comment]
I just opened a [PR](https://github.com/valkey-io/valkey-py/pull/136) for this issue.
