### ISSUE TITLE
change destination_db's type constraint in copy() method ?

### ISSUE THREAD

**Issue by spyinx** [valkey-io/valkey-py#138]
when i read code in copy() method, i found destination_db can be int type and works well, but the type constraint hints it can only be str or None：
```python
>>> from valkey import Valkey
>>> r = Valkey(host="127.0.0.1", port=6888, password='xxxxx')
>>> r.copy("hello", "abc", 1, True)
True
>>> r.copy("hello", "abc", "1", True)
True
```

https://github.com/valkey-io/valkey-py/blob/c490780a1d7b629317e5c0d976ec13dd64de8e55/valkey/commands/core.py#L1661-L1667

so, i think this can be changed like this：
```
destination_db: Optional[Union[int, str]] = None,
or 
destination_db: Union[int, str, None] = None,
```

**Comment by aiven-sal** [comment]
Hi! Thank you for reporting. Your proposal sounds correct to me. Would you like to create a PR for this?

**Comment by spyinx** [comment]
> Hi! Thank you for reporting. Your proposal sounds correct to me. Would you like to create a PR for this?

i will create a pr to fix this issue, thanks for your reply

**Comment by spyinx** [comment]
@aiven-sal move() method have the same problem, the db param constraint to int, but str also works fine：
```python
>>> r.move("hello", "3")
True
```

**Comment by amirreza8002** [comment]
hi
there are a lot of problems with the type hints of this package, since it inherits from `redis-py`
me and some other people are thinking of fixing some parts, you can join if you like.

see https://github.com/valkey-io/valkey-py/pull/134 for more

**Comment by spyinx** [comment]
> hi there are a lot of problems with the type hints of this package, since it inherits from `redis-py` me and some other people are thinking of fixing some parts, you can join if you like.
> 
> see #134 for more

ok, since you are working on it, i will not focus on this, i just read the code and see the problem. thanks for your work. Now i'm not familiar with the code and need time to learn more. if i have the ability, then i can join the community to fix bugs.

**Comment by aiven-sal** [comment]
> > hi there are a lot of problems with the type hints of this package, since it inherits from `redis-py` me and some other people are thinking of fixing some parts, you can join if you like.
> > see #134 for more
> 
> ok, since you are working on it, i will not focus on this, i just read the code and see the problem. thanks for your work. Now i'm not familiar with the code and need time to learn more. if i have the ability, then i can join the community to fix bugs.

Hi! This contribution is welcome. You don't _have_ to join the work in #134, unless you want to do it. #134 is a valiant effort from the community to fix typing, but it will take a lot of time. In the mean time we will merge small PRs that fix obvious typing issues.

**Comment by spyinx** [comment]
Thank you all for taking care of the newcomers. I am still working hard on the code and hope to have the opportunity to fix bugs for the community in the future
