### ISSUE TITLE
getex() method has a error when verify parameters

### ISSUE THREAD

**Issue by spyinx** [valkey-io/valkey-py#142]
when i read code in getex() method, i found that use set to check mutually exclusive between options may not be right：
https://github.com/valkey-io/valkey-py/blob/c490780a1d7b629317e5c0d976ec13dd64de8e55/valkey/commands/core.py#L1862-L1867

if ex and px has the same value, this condition will be False：
```python
>>> from valkey import Valkey
>>> v = Valkey(host='127.0.0.1', port=6888, password='xxxx')
>>> v.getex("hello", 10, 10)
Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    v.getex("hello", 10, 10)
    ~~~~~~~^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/env-3.13/lib/python3.13/site-packages/valkey/commands/core.py", line 1895, in getex
    return self.execute_command("GETEX", name, *pieces)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/env-3.13/lib/python3.13/site-packages/valkey/client.py", line 570, in execute_command
    response = conn.retry.call_with_retry(
        lambda: self._send_command_parse_response(
    ...<2 lines>...
        lambda error: self._disconnect_raise(conn, error),
    )
  File "/root/.pyenv/versions/env-3.13/lib/python3.13/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/root/.pyenv/versions/env-3.13/lib/python3.13/site-packages/valkey/client.py", line 571, in <lambda>
    lambda: self._send_command_parse_response(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        conn, command_name, *args, **options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/root/.pyenv/versions/env-3.13/lib/python3.13/site-packages/valkey/client.py", line 543, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/env-3.13/lib/python3.13/site-packages/valkey/client.py", line 590, in parse_response
    response = connection.read_response()
  File "/root/.pyenv/versions/env-3.13/lib/python3.13/site-packages/valkey/connection.py", line 570, in read_response
    raise response
valkey.exceptions.ResponseError: syntax error
>>> 
```
so i think use list instead of set will be more accurate, although it's not simple enough：
```python
        opvset = [1 for op in [ex, px, exat, pxat] if op is not None]
        if sum(opvset) > 1 or (sum(opvset) and persist):
            raise DataError(
                "``ex``, ``px``, ``exat``, ``pxat``, "
                "and ``persist`` are mutually exclusive."
            )
```

**Comment by aiven-sal** [comment]
Nice find! Thank you very much!
I think would like the fix to look more like:
```
        opvset = sum(op is not None for op in [ex, px, exat, pxat])
        if opvset > 1 or (opvset and persist):
            raise DataError(
                "``ex``, ``px``, ``exat``, ``pxat``, "
                "and ``persist`` are mutually exclusive."
            )
```

**Comment by spyinx** [comment]
> Nice find! Thank you very much!
> I think I would like the fix to look more like:
> ```python
>         opvset = sum(op is not None for op in [ex, px, exat, pxat])
>         if opvset > 1 or (opvset and persist):
>             raise DataError(
>                 "``ex``, ``px``, ``exat``, ``pxat``, "
>                 "and ``persist`` are mutually exclusive."
>             )
> ```

that's look simpler than my code，can i      make a pr for this issue and does this fix need a test case or not? Now i have no expirence in writing test case and i need some time to read test code in valkey-py.

**Comment by amirreza8002** [comment]
first run the tests, if something breaks, you have a lead

**Comment by spyinx** [comment]
> first run the tests, if something breaks, you have a lead 

thanks, i will try it later

**Comment by mkmkme** [comment]
Also it's worth adding your scenario as a new test case for `getex` to verify it will raise `DataError` and not `ResponseError`

**Comment by aiven-sal** [comment]
You can also take advantage of GitHub CI: enable actions in your own fork and create a pr there before you create it here. So you can easily run all tests on your own (if you find it difficult to run tests locally, especially since some things can only run as GH actions).

**Comment by aiven-sal** [comment]
You just need to add a few lines to [this test case](https://github.com/valkey-io/valkey-py/blob/8d9470d6287761948820712ee22f45da2f7b964c/tests/test_commands.py#L1331), something along the lines of [this](https://github.com/valkey-io/valkey-py/blob/8d9470d6287761948820712ee22f45da2f7b964c/tests/test_commands.py#L1633).
