### ISSUE TITLE
`Valkey.set()` checks

### ISSUE THREAD

**Issue by amirreza8002** [valkey-io/valkey-py#143]
hi

if we pass both `ex` and `px` to [set](https://github.com/valkey-io/valkey-py/blob/main/valkey/commands/core.py#L2248), it will be passed down to valkey, which thros a syntax error, but the error is not descriptive, so maybe adding a check would be good.

also there is no type check for [exat](https://github.com/valkey-io/valkey-py/blob/main/valkey/commands/core.py#L2307) and [pxat](https://github.com/valkey-io/valkey-py/blob/main/valkey/commands/core.py#L2312) and [keepttl](https://github.com/valkey-io/valkey-py/blob/main/valkey/commands/core.py#L2317) and [nx and xx](https://github.com/valkey-io/valkey-py/blob/main/valkey/commands/core.py#L2320-L2323)

also [get](https://github.com/valkey-io/valkey-py/blob/main/valkey/commands/core.py#L2325-L2327) looks like a bug, it should be the value of get that is passed down, not hardcoded `True`

the `options` dict also seems un-needed

let me know what you think

**Comment by amirreza8002** [comment]
> I'm not sure what you mean. I don't think we validate types anywhere, except in the broken type annotations. If it quacks like a duck, it is a duck.

since `set()` checks the type of `ex` and `px` i mentioned that, but it's not that important

i'll write up something to check the first problem

**Comment by aiven-sal** [comment]
> > I'm not sure what you mean. I don't think we validate types anywhere, except in the broken type annotations. If it quacks like a duck, it is a duck.
> 
> since `set()` checks the type of `ex` and `px` i mentioned that, but it's not that important

Oh right! I missed that. Well then we can add something similar for exat and pxat.

> i'll write up something to check the first problem

thanks!
