### ISSUE TITLE
Codecov doesn't work anymore

### ISSUE THREAD

**Issue by aiven-sal** [valkey-io/valkey-py#21]
CI integration with codecov stopped working.

**Comment by ahmedsobeh** [comment]
Looks like codecov is back, working in PR #32

**Comment by aiven-sal** [comment]
It looks like it only runs on @mkmkme's PRs

**Comment by ahmedsobeh** [comment]
I can also see it in #34 and #33

**Comment by aiven-sal** [comment]
True, than I think that it only runs when the PR branch is from a different repo. And doesn't run when someone creates a PR from a branch of this repo. Maybe there is a way to change this.

**Comment by aiven-sal** [comment]
The problem seems to be that we don't have a token configured for codecov.
When the PR is created from a forked repo that is not a problem:
https://github.com/valkey-io/valkey-py/actions/runs/9790645272/job/27032704017#step:6:44 
>  The PR is happening in a forked repo. Using tokenless upload.

But when it is created from a branch of this repo we get:
https://github.com/valkey-io/valkey-py/actions/runs/9849442033/job/27193107167#step:6:38
> Error: Codecov token not found.

So we need to obtain a token and configure as a secret for the repo.

**Comment by ahmedsobeh** [comment]
> So we need to obtain a token and configure it as a secret for the repo.

DO you have access to the codecov account we're using? I guess that's the only way to create the token

**Comment by aiven-sal** [comment]
> DO you have access to the codecov account we're using? I guess that's the only way to create the token

Nope. I'll ask if someone can help.
