### ISSUE TITLE
Update PR Template to no longer request updating the Changes File/Potentially Remove the CHANGES file 

### ISSUE THREAD

**Issue by kjaymiller** [valkey-io/valkey-py#31]
Based on the comment in PR #27

> 2) ignore the CHANGES file, it wasn't really used much recently and we have a nice bot that can summarize changes in releases from PRs. It isn't perfect, but for now let's just use that (you don't have to do anything).

_Originally posted by @aiven-sal in https://github.com/valkey-io/valkey-py/pull/27#pullrequestreview-2147424838_

**Comment by aiven-sal** [comment]
We should also add a not inside the CHANGES file to make it clear that it isn't used anymore.
