### ISSUE TITLE
Flaky test_geo*

### ISSUE THREAD

**Issue by aiven-sal** [valkey-io/valkey-py#39]
Some tests that match `test_geo*` in `tests/test_commands.py` and `tests/test_asyncio/test_commands.py` are not reliable.
We never observed them failing in CI or locally, but I received reports that they failed in some occasions.

These tests expect exact matches between floats e.g.

https://github.com/valkey-io/valkey-py/blob/6c95904b07bee87f6a6fd736a8557f166e48de53/tests/test_commands.py#L3544-L3563

And this doesn't always work.

According to the reports I received, the values are usually off by ~1e-15

Floats should be compared using [math.isclose](https://docs.python.org/3/library/math.html#math.isclose). The default tolerance should be enough.

**Comment by aiven-sal** [comment]
These are the tests that have been reported as flaky:
```
FAILED tests/test_commands.py::TestValkeyCommands::test_geopos - assert [(2.1...
FAILED tests/test_commands.py::TestValkeyCommands::test_geosearch_member - As...
FAILED tests/test_commands.py::TestValkeyCommands::test_geosearch_with - Asse...
FAILED tests/test_commands.py::TestValkeyCommands::test_geosearchstore_dist
FAILED tests/test_commands.py::TestValkeyCommands::test_georadius_with - Asse...
FAILED tests/test_commands.py::TestValkeyCommands::test_georadius_store_dist
FAILED tests/test_commands.py::TestValkeyCommands::test_georadiusmember - Ass...
FAILED tests/test_asyncio/test_commands.py::TestValkeyCommands::test_geopos[single]
FAILED tests/test_asyncio/test_commands.py::TestValkeyCommands::test_geopos[pool]
FAILED tests/test_asyncio/test_commands.py::TestValkeyCommands::test_georadius_with[single]
FAILED tests/test_asyncio/test_commands.py::TestValkeyCommands::test_georadius_with[pool]
FAILED tests/test_asyncio/test_commands.py::TestValkeyCommands::test_georadius_store_dist[single]
FAILED tests/test_asyncio/test_commands.py::TestValkeyCommands::test_georadius_store_dist[pool]
FAILED tests/test_asyncio/test_commands.py::TestValkeyCommands::test_georadiusmember[single]
FAILED tests/test_asyncio/test_commands.py::TestValkeyCommands::test_georadiusmember[pool]
```

here is the full build: https://koji.fedoraproject.org/koji/taskinfo?taskID=120194663

The error happens on s390x, it may be impossible to reproduce on other architectures.

**Comment by kjaymiller** [comment]
would testing on a docker image as mentioned in the link below work?

https://docs.gitlab.com/omnibus/development/s390x.html#vm-provisioning

I should have a PR in today or tomorrow and can take a little more time to try and run on this if you believe it will effectively test.
