### ISSUE TITLE
incompatiable code with redis py

### ISSUE THREAD

**Issue by amirreza8002** [valkey-io/valkey-py#82]
hi
so i want to fork django-redis package and turn into django-valkey
[this](https://github.com/redis/redis-py/blob/master/redis/connection.py#L937-L1016) parts of redis_py package is not available in your project.
some parts of it are used in django-redis so i was wondering if there is a reason why these are not presented.

**Version**: latest

**Comment by aiven-sal** [comment]
Hi Amirreza! Thanks for reaching out.
Since the fork happend, valkey-py and redis-py diverged a little bit.
They are still very similar, but they are also evolving independently.
I think that the code you are looking for is now here:
https://github.com/valkey-io/valkey-py/blob/fd7a56a8b9abcabe1f2b1e148244b8fcc7db4382/valkey/_parsers/url_parser.py#L14-L100

**Comment by amirreza8002** [comment]
oh thanks 
it makes sense 
i was assuming that the projects go exactly the same way for the moment 

I'll fix the import then

**Comment by aiven-sal** [comment]
No problem, 
feel free to re-open this issue if you encounter any other problem.

**Comment by amirreza8002** [comment]
hello @aiven-sal 
i wanted to know what version of python are you supporting?
i have some typing headaches coming from valkey_py and wanted to write a patch
need to know what syntax i can and can't use

**Comment by aiven-sal** [comment]
We support from 3.8 to 3.12 (https://github.com/valkey-io/valkey-py/blob/main/setup.py#L50-L54),
BTW there is another issue related to typing you if you want to take a look https://github.com/valkey-io/valkey-py/issues/84

**Comment by amirreza8002** [comment]
ah i was hoping for 3.10 to use `|` :)

ok then

also i know you are busy but if you ever find the time to reflect on django-valkey i would very much appreciate it
I'm new to caching and still trying to figure out stuff

**Comment by aiven-sal** [comment]
> ah i was hoping for 3.10 to use `|` :)

I think it will probably take a couple of years before we drop 3.9. :(


> also i know you are busy but if you ever find the time to reflect on django-valkey i would very much appreciate it I'm new to caching and still trying to figure out stuff

What do you mean by "reflect on django-valkey" ?

**Comment by amirreza8002** [comment]
ah i just meant feedback on what can be added or fixed on the project
which i just realize i hadn't posted the link before 
[](https://github.com/amirreza8002/django-valkey)

but again
i understand that it's not a small codebase and you are busy, so don't feel pressure

**Comment by aiven-sal** [comment]
I'm not very much involved in django development.
I'd suggest to reach out to the original django-redis's devs. They might have some feedback and they may be even interested in cooperating on django-valkey.
